name: michaelhollar
favicon: null
layout_spectrum: 0.5891894018277526
typography_spectrum: 0.25083921710029244
title: Thinking it Through
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4e5359'
    - '#d3d4d9'
    - '#bdaa64'
    - '#7185aa'
  brandStrength: 0.5183651524130255
  lightness: 0.03352175885811448
  saturation: 0.29728027642704546
  rhythmicContrast: 0.8184872528072447
purpose: []
