name: michaelhollar
favicon: null
layout_spectrum: 0.50223
typography_spectrum: 0.55853
title: Thinking it Through
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4e5359'
    - '#d3d4d9'
    - '#bdaa64'
    - '#7185aa'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
